name: deploy-staging
on:
  push:
    branches:
      - staging
permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Create deploy file
        run: |
          set -e

          # Limpiar residuos previos
          rm -rf public deploy.tar.gz

          # Astro genera el build en dist/
          mkdir -p public
          cp -r dist/* public/

          # Crear paquete de despliegue
          tar -czf deploy.tar.gz public

      - name: Backup on hosting web old
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.IONOS_HOST }}
          username: ${{ secrets.IONOS_USERNAME }}
          key: ${{ secrets.IONOS_SSH_KEY }}
          passphrase: ${{ secrets.IONOS_SSH_PASSPHRASE }}
          port: ${{ secrets.IONOS_PORT }}
          script: |
            if [ -d "/var/www/staging.slensys.com.mx/public_html_backup" ]; then
              rm -rf /var/www/staging.slensys.com.mx/public_html_backup
            fi
            if [ -d "/var/www/staging.slensys.com.mx/public_html" ]; then
              cp -r /var/www/staging.slensys.com.mx/public_html /var/www/staging.slensys.com.mx/public_html_backup
            fi
  
            mkdir -p /var/www/staging.slensys.com.mx/temp_deploy

      - name: Upload files
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.IONOS_HOST }}
          username: ${{ secrets.IONOS_USERNAME }}
          key: ${{ secrets.IONOS_SSH_KEY }}
          passphrase: ${{ secrets.IONOS_SSH_PASSPHRASE }}
          port: ${{ secrets.IONOS_PORT }}
          source: "deploy.tar.gz"
          target: "/var/www/staging.slensys.com.mx/temp_deploy/"

      - name: Extract files
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.IONOS_HOST }}
          username: ${{ secrets.IONOS_USERNAME }}
          key: ${{ secrets.IONOS_SSH_KEY }}
          passphrase: ${{ secrets.IONOS_SSH_PASSPHRASE }}
          port: ${{ secrets.IONOS_PORT }}
          script: |
            set -e
            cd /var/www/staging.slensys.com.mx/temp_deploy
            tar -xzf deploy.tar.gz
            rm deploy.tar.gz
            
            if [ ! -d "../public_html" ]; then
              mkdir -p ../public_html
            fi
            
            # Copiar el public con el nuevo index.php
            rm -rf ../public_html/*
            cp -r public/* ../public_html/
